[package]
name = "cvalid"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
calamine = "0.21.2"
clap = { version = "4.3.19", features = ["derive"] }
